version: "3.8"
services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=acsify
      - POSTGRES_PASSWORD=acsify
      - POSTGRES_DB=acsify
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
